✨ Feature - 공격 패킷 로그 저장 api 생성
CSID-DGU/Re-MLAC pull request #11
Opened 2024-03-03 12:02 UTC by dlawjddn

## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #7 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- boiler plate 생성
- 공격 패킷 로그 도메인 생성
- 공격 패킷 로그 api 생성

2024-03-04 02:36 UTC, nykoh2001 reviewed
👍🏻

2024-03-04 04:40 UTC, HyungJoonSon commented on src/main/resources/application.yml
> +>>>>>>> c777e19d721107938e7eca9415a8b35a609679c3
이부분 수정해야할 거 같습니다~~

2024-03-04 04:40 UTC, HyungJoonSon requested changes
충돌난 부분 지우고 다시 올려주세요~~

2024-03-04 06:11 UTC, dlawjddn commented on src/main/resources/application.yml
> +>>>>>>> c777e19d721107938e7eca9415a8b35a609679c3
수정해서 다시 올렸습니당~ 확인해주세요~

2024-03-04 06:12 UTC, kurtyoon reviewed
LGTM :)

2024-03-05 13:10 UTC, jjuuuunnii commented
🫡

2024-03-06 01:41 UTC, kurtyoon approved these changes

2024-03-06 10:44 UTC, nykoh2001 approved these changes

2024-03-07 09:26 UTC, HyungJoonSon approved these changes
고생하셨습니다

2024-03-07 09:26 UTC, merged