feat: create extra explanation
CSID-DGU/Re-MLAC pull request #59
Opened 2024-04-03 13:26 UTC by jjuuuunnii

## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #58 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- 각 코드 주석 추가
- webserver enum 변경

2024-04-03 13:27 UTC, nykoh2001 approved these changes
👍🏻

2024-04-03 13:28 UTC, dlawjddn approved these changes
네 ENUM~ 

확인했습니다 ~!

2024-04-03 18:13 UTC, kurtyoon requested changes
요청사항 반영해서 다시 올려주세요!

2024-04-03 18:13 UTC, kurtyoon commented on virtual-web-server/src/main/java/org/dongguk/mlac/dto/type/ELogStatus.java
> +    UNBLOCK("UNBLOCK");
파이프라인이 Block이라는 표현 보다는 생성되었다는 표현이 더 나은 것 같습니다. 상태는 Null 혹은 Create 이 두 상태가 존재하지 않을까요?

2024-04-04 06:35 UTC, HyungJoonSon commented on origin-server/src/main/java/org/dongguk/mlac/service/PacketLogService.java
> +    // 이벤트를 받아 Pass된 packetLog 생성
이부분 /** */ 형태로 작성!

2024-04-04 06:36 UTC, hyungjoon-son commented on virtual-firewall/src/main/java/org/dongguk/mlac/service/FirewallLogService.java
> +    // 이벤트를 받아 firewallLog 생성
위와 동일합니다 /** */ 형태로 Comment 만들기!

2024-04-04 06:36 UTC, HyungJoonSon commented on virtual-web-application-server/src/main/java/org/dongguk/mlac/service/WebApplicationLogService.java
> +    // 이벤트를 받아 WebApplicationLog 생성
위와 동일합니다!

2024-04-04 06:36 UTC, HyungJoonSon commented on virtual-web-server/bin/main/application.yml
> +---
이 파일이 왜 여기 있죠...?

2024-04-04 06:37 UTC, HyungJoonSon commented on virtual-web-server/src/main/java/org/dongguk/mlac/dto/type/ELogStatus.java
> +    UNBLOCK("UNBLOCK");
저도 동일한 의견입니다

2024-04-04 06:37 UTC, HyungJoonSon commented on virtual-web-server/src/main/java/org/dongguk/mlac/service/WebServerLogService.java
> +    // 이벤트를 받아 WebServerLog 생성
함수 명 변경한 것은 좋지만, 주석에 위와 동일하게 /** */하면 좋을 거 같습니다.

2024-04-04 06:38 UTC, HyungJoonSon requested changes
Comment 반영 부탁드립니다~~

2024-04-04 11:08 UTC, kurtyoon approved these changes
good bb

2024-04-05 16:33 UTC, HyungJoonSon approved these changes
수고하셨습니다

2024-04-05 16:37 UTC, merged